### ISSUE TITLE
How to evaluate the quality of generated text

### ISSUE THREAD

**Issue by bansky-cl** [thorinf/simple-diffusion-lm#8]
What great and simple code!   But I have some confusion on it.

- when i train the model,  each epoch will generate 'num_examples=8' samples. how can i  evaluate the quality of generated text ? Or you can tell me some metrics to evaluate it.

**Comment by thorinf** [comment]
This is something i need to add. So unconditioned text generation is quite hard to get metrics on, scores like BLEU require reference text which unconditioned doesnt have. 

What I need to do is add conditional generation support and ask the model the complete the sentence, then I can use test data to evaluate the model.

**Comment by bansky-cl** [comment]
thks. I also will try some conditional text diffusion. looking forward to your implementation on conditional gen.

**Comment by thorinf** [comment]
Just want to say that current results from this aren't spectacular, its been hard to get good sentences from any variants I've worked on. I've also tried other methods/repos, and it's a similar story
